### ISSUE TITLE
Do we really need categories?

### ISSUE THREAD

**Issue by worldspawn-web** [SeenKid/bunny-hop.net#2]
The website is focused on bunny-hop gamemode, but there is a gamemode column in communities.
Are we planning on implementing other gamemode communities?
If no, then do we really need categories here?

Maybe we should re-place It with something other? Like region, for example.

![image](https://github.com/SeenKid/bunny-hop.net/assets/116187256/01d86765-e7a5-414a-ad86-12f5346561fb)

**Comment by SeenKid** [comment]
nah

**Comment by worldspawn-web** [comment]
@SeenKid what do you think then about re-placing the column with country/region flags?

**Comment by SeenKid** [comment]
good idea

**Comment by SeenKid** [comment]
also images are not working 
![CleanShot 2023-11-02 at 09 48 16](https://github.com/SeenKid/bunny-hop.net/assets/30565751/fc5c1f57-2a2d-49c1-bb2e-63132602b44e)

**Comment by worldspawn-web** [comment]
@SeenKid 

> also images are not working 

As I answered before in DMs, the issue is most likely with the project architecture on the host, not the github repository.
Check that folders structure matches the structure in the main branch, or just change the const `imgPath` for your needs.
